### ISSUE TITLE
Issue when opening binary simulation results

### ISSUE THREAD

**Issue by sebasj13** [davidchall/topas2numpy#10]
Hi,
I'm experiencing an issue when trying to open the attached binary simulation result:
[TDK_0.zip](https://github.com/davidchall/topas2numpy/files/8948712/TDK_0.zip)

The error message I receive is:
![Error](https://user-images.githubusercontent.com/87897942/174796223-a7dac17b-ae0c-4e6d-9889-d5449c863c73.png)

Thanks!

**Comment by davidchall** [comment]
Hi @sebasj13,

Looking at the header file, I see the expected output dimensions are 1 x 1 x 160 bins and there are 5 output statistics. So overall you should expect to find 160 x 5 = 800 values in the binary file. The error you've encountered suggests it has only found 42 values in the binary file.

I'm no longer a Topas developer (or user), so unfortunately I can't really help debug beyond this. I'd recommend trying to output in csv format so it's easier to see what's going on (e.g., do you see 800 values in the csv file?)

**Comment by sebasj13** [comment]
Hi @davidchall,
 Thanks for your response. The equivalent .csv file did not have any issues opening. I'll try to investigate further!
