### ISSUE TITLE
Detect best NumPy dtype (use unsigned int for SurfaceTrackCount)

### ISSUE THREAD

**Issue by murdock-grewar** [davidchall/topas2numpy#8]
When the TOPAS scorer mode is set to 'SurfaceTrackCount' then the result is an integer. It would be best if the numpy dtype of the loaded data was set to an unsigned integer type in this case. 

It seems this library loads such arrrays as 'float64' type which uses only 53 of the 64 bits to store the mantissa, meaning 11/64 bits are wasted in the case of 'SurfaceTrackCount', which unecessarily increases filesize.

It's also unexpected to receive a NumPy array of type 'float64' when the data consists of unsigned integers so this may have a usability impact also.

Is it possible to change this library so that it bases the data type whether the scorer is 'SurfaceTrackCount' or something else?

**Comment by davidchall** [comment]
Hi @murdock-grewar, this feature has been added in the development version.
